### ISSUE TITLE
kits issues

### ISSUE THREAD

**Issue by benjaelbsrboi** [Kr4ken-9/NewEssentials#45] opened 2021-03-05 22:41 UTC
when u crate a kit, the things is been drop inmediatly and isnt equip automatically, please fix it

**Comment by Kr4ken-9** [comment] 2021-03-06 02:30
I believe this issue is related to OpenMod, I will open an issue in that repo and link it here.

**Comment by Trojaner** [comment] 2021-03-06 03:00
Can confirm issue is related to OpenMod itself, will try to fix tomorrow

**Comment by IAmSilK** [comment] 2021-03-07 07:44
Fixed for the next OpenMod update

**Comment by Trojaner** [comment] 2021-03-07 10:12
Closing here since the issue is fixed in OpenMod

**Closed by Trojaner** 2021-03-07 10:12 UTC
Labels: bug
